name: st_crud
description: "A new Flutter project with CRUD functionality using Supabase."
publish_to: 'none' # Keeps the project private (Remove this to publish to pub.dev)

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: 2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
